name: identity_client
version: 1.0.0+1
description: A Identity client for Dart.
publish_to: none

dependencies:
  dio: ^3.0.9
  fresh_dio: ^0.2.0
  meta: ^1.1.8
  flutter_secure_storage: ^3.3.3
  
dev_dependencies:

environment:
  sdk: ">=2.7.0 <3.0.0"
